# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  container: 
    image: circleci/node:14.15.4
    name: react-ssr-advanced
  vmImage: 'macOS-latest'

## Multi-container support here
services:
  postgres:
    image: circleci/postgres:9.6.16-alpine
    ports:
      - "5432:5432"
    volumes:
    - db-data:/var/lib/postgresql/data
    env:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
## End multi-container

steps:
- script: |
    npm install codecov
    npm install
    npm test
    npm run build:frontend
    npm run build:backend:ci
    npx codecov
  displayName: 'npm install and build'
- script: |
    sudo snap install --classic heroku
    heroku login
    heroku stack:set heroku-18
    cd docker/backend/prod
    heroku container:login
    heroku container:push web --app=react-ssr-nest-api
    heroku container:release web --app=react-ssr-nest-api
  displayName: 'Deploy Backend Build'