# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

## Multi-container support here
services:
  postgres:
    image: circleci/postgres:9.6.13-alpine
    volumes:
    - db-data:/var/lib/postgresql/data
    env:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
## End multi-container

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g codecov
    npm install
    npm test
    npm run build:frontend
    codecov
  displayName: 'npm install and build'
