version: "3"

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
  
  frontend:
    hostname: frontend
    depends_on:
      - postgres
    build: ./docker/frontend/prod
    environment:
      - API_URL="http://localhost:1234"
      - API_DB_HOST=postgres
      - API_DB_PORT=5432
      - API_DB_USERNAME=postgres
      - API_DB_PASSWORD=password
      - API_DB_NAME=postgres
    ports: 
      - 8080:80
      
networks:
  chainnet:
    driver: bridge
    ipam:
      config:
      - subnet: 172.25.0.0/24   
    
